# Change these first
owner: JulienJourdain # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Julien's tech blog
    url: https://blog.cloud.jourdain.io
  - name: Dietetfit
    url: https://dietetfit.fr
  - name: Dietetfit Beta
    url: https://dietetfit.cloud.jourdain.io

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Julien's** endpoints uptime monitor and status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
